name: Run Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Pytest and Generate Allure Reports
        run: |
          pytest --alluredir=allure-results

      - name: Install Allure
        run: |
          curl -o allure-2.24.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz

      - name: Generate Allure Report
        run: |
          ./allure-2.24.0/bin/allure generate allure-results -o allure-report --clean

      - name: Upload Allure Report as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

