name: Test Automation CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Automated Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js (for JavaScript-based automation)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install  # or yarn install, pip install -r requirements.txt for Python, etc.

      - name: Run Unit Tests
        run: npm test  # Replace with your test command

      - name: Run API Tests (if applicable)
        run: npm run test:api  # Modify as per your setup

      - name: Run Database Tests (if applicable)
        run: npm run test:db  # Modify accordingly

      - name: Generate Allure Report (if using Allure)
        run: npm run allure:generate  # Modify if different

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/

  deploy:
    name: Deploy Automation Framework
    needs: test  # Deploy only if tests pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server (Example)
        run: echo "Deploying Automation Framework..."
